export default allExchanges = [
  {
    "id": "gdax",
    "name": "Coinbase Exchange",
    "year_established": 2012,
    "country": "United States",
    "description": "",
    "url": "https://www.coinbase.com",
    "image": "https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1621471875",
    "has_trading_incentive": false,
    "trust_score": 10,
    "trust_score_rank": 1,
    "trade_volume_24h_btc": 28841.475892536055,
    "trade_volume_24h_btc_normalized": 28841.475892536055
  },
  {
    "id": "bybit_spot",
    "name": "Bybit",
    "year_established": 2018,
    "country": "British Virgin Islands",
    "description": "Bybit is a cryptocurrency exchange that offers a professional platform featuring an ultra-fast matching engine, excellent customer service and multilingual community support for crypto traders of all levels. Established in March 2018, Bybit currently serves more than 10 million users and institutions offering access to over 100 assets and contracts across Spot, Futures and Options, launchpad projects, earn products, an NFT Marketplace and more. Bybit is a proud partner of Formula One racing team, Oracle Red Bull Racing, esports teams NAVI, Astralis, Alliance, Virtus.pro, Made in Brazil (MIBR), City Esports, and Oracle Red Bull Racing Esports, and association football (soccer) teams Borussia Dortmund and Avispa Fukuoka.",
    "url": "https://www.bybit.com",
    "image": "https://assets.coingecko.com/markets/images/698/small/bybit_spot.png?1629971794",
    "has_trading_incentive": false,
    "trust_score": 10,
    "trust_score_rank": 2,
    "trade_volume_24h_btc": 31863.636071976984,
    "trade_volume_24h_btc_normalized": 27602.460077704534
  },
  {
    "id": "kucoin",
    "name": "KuCoin",
    "year_established": 2014,
    "country": "Seychelles",
    "description": "",
    "url": "https://www.kucoin.com/",
    "image": "https://assets.coingecko.com/markets/images/61/small/kucoin.png?1640584259",
    "has_trading_incentive": false,
    "trust_score": 10,
    "trust_score_rank": 3,
    "trade_volume_24h_btc": 19259.70682039493,
    "trade_volume_24h_btc_normalized": 14422.916194531488
  },
  {
    "id": "huobi",
    "name": "Huobi",
    "year_established": 2013,
    "country": "Seychelles",
    "description": "",
    "url": "https://www.huobi.com",
    "image": "https://assets.coingecko.com/markets/images/25/small/logo_V_colour_black.png?1669177364",
    "has_trading_incentive": false,
    "trust_score": 10,
    "trust_score_rank": 4,
    "trade_volume_24h_btc": 13334.276685123463,
    "trade_volume_24h_btc_normalized": 13334.276685123463
  },
  {
    "id": "kraken",
    "name": "Kraken",
    "year_established": 2011,
    "country": "United States",
    "description": "",
    "url": "https://r.kraken.com/c/2223866/687155/10583",
    "image": "https://assets.coingecko.com/markets/images/29/small/kraken.jpg?1584251255",
    "has_trading_incentive": false,
    "trust_score": 10,
    "trust_score_rank": 5,
    "trade_volume_24h_btc": 12104.90089296869,
    "trade_volume_24h_btc_normalized": 8779.037986310457
  },
  {
    "id": "bitfinex",
    "name": "Bitfinex",
    "year_established": 2014,
    "country": "British Virgin Islands",
    "description": "",
    "url": "https://www.bitfinex.com",
    "image": "https://assets.coingecko.com/markets/images/4/small/BItfinex.png?1615895883",
    "has_trading_incentive": false,
    "trust_score": 10,
    "trust_score_rank": 6,
    "trade_volume_24h_btc": 2786.366991625779,
    "trade_volume_24h_btc_normalized": 2786.366991625779
  },
  {
    "id": "crypto_com",
    "name": "Crypto.com Exchange",
    "year_established": 2019,
    "country": "Malta",
    "description": "Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards",
    "url": "https://crypto.com/exchange",
    "image": "https://assets.coingecko.com/markets/images/589/small/h2oMjPp6_400x400.jpg?1669699705",
    "has_trading_incentive": false,
    "trust_score": 10,
    "trust_score_rank": 7,
    "trade_volume_24h_btc": 2740.663254706374,
    "trade_volume_24h_btc_normalized": 2740.663254706374
  },
  {
    "id": "binance",
    "name": "Binance",
    "year_established": 2017,
    "country": "Cayman Islands",
    "description": "",
    "url": "https://www.binance.com/",
    "image": "https://assets.coingecko.com/markets/images/52/small/binance.jpg?1519353250",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 8,
    "trade_volume_24h_btc": 246426.87580775013,
    "trade_volume_24h_btc_normalized": 102665.20175660713
  },
  {
    "id": "gate",
    "name": "Gate.io",
    "year_established": null,
    "country": "Cayman Islands",
    "description": "Gate was established in 2013, and it is the top 10 exchanges in the world in terms of authentic trading volume. It is also the first choice of over 8 million registered customers, covering 130+ countries worldwide, as we are providing the most comprehensive digital asset solutions.",
    "url": "https://gate.io/",
    "image": "https://assets.coingecko.com/markets/images/60/small/gate_io_logo1.jpg?1654596784",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 9,
    "trade_volume_24h_btc": 19076.74116668477,
    "trade_volume_24h_btc_normalized": 18620.23827574771
  },
  {
    "id": "mxc",
    "name": "MEXC",
    "year_established": 2018,
    "country": "Seychelles",
    "description": "Established in April 2018, MEXC is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.",
    "url": "https://www.mexc.com/",
    "image": "https://assets.coingecko.com/markets/images/409/small/MEXC_logo_square.jpeg?1673000123",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 10,
    "trade_volume_24h_btc": 20739.535694702037,
    "trade_volume_24h_btc_normalized": 15796.810335330438
  },
  {
    "id": "okex",
    "name": "OKX",
    "year_established": 2017,
    "country": "Seychelles",
    "description": "",
    "url": "https://www.okx.com",
    "image": "https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1642428377",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 11,
    "trade_volume_24h_btc": 30166.1977246393,
    "trade_volume_24h_btc_normalized": 14469.941558871988
  },
  {
    "id": "bingx",
    "name": "BingX",
    "year_established": 2018,
    "country": "British Virgin Islands",
    "description": "Founded in 2018, BingX is a global digital asset, spot, and derivatives trading platform that provides a user-centric and open ecosystem with intuitive social trading features.\r\nCreated to enrich the entire cryptocurrency industry, BingX is a safe, reliable, and user-friendly venue for users to trade their favorite assets.",
    "url": "https://bingx.com/",
    "image": "https://assets.coingecko.com/markets/images/812/small/YtFwQwJr_400x400.jpg?1646056092",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 12,
    "trade_volume_24h_btc": 9511.89907580819,
    "trade_volume_24h_btc_normalized": 9511.89907580819
  },
  {
    "id": "binance_us",
    "name": "Binance US",
    "year_established": 2019,
    "country": "United States",
    "description": "",
    "url": "https://www.binance.us/",
    "image": "https://assets.coingecko.com/markets/images/469/small/Binance.png?1568875842",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 13,
    "trade_volume_24h_btc": 1961.8765908999492,
    "trade_volume_24h_btc_normalized": 1961.8765908999492
  },
  {
    "id": "phemex",
    "name": "Phemex",
    "year_established": 2019,
    "country": "Singapore",
    "description": "Launched in 2019, Phemex is a Singapore-based cryptocurrency and derivatives trading platform led by former Morgan Stanley executives. Serving around 5 million active users in over 200 countries, Phemex supports 150+ trading pairs with up to 100x leverage.\r\n\r\n-  Fee Structure: 0.1% for both maker and taker\r\n-  Contract Fee Structure: 0.01% for maker and 0.06% for taker\r\n-  Up to $100 Welcome Bonus for new users\r\n-  Earn up to 8.5% APY interest income on crypto assets\r\n-  Free academy with 450+ carefully curated articles about crypto & trading\r\n-  Security: Hierarchical Deterministic Cold Wallet System with 2-level human scrutiny offline signatures.",
    "url": "https://phemex.com/",
    "image": "https://assets.coingecko.com/markets/images/564/small/Phemex_logo_4.png?1641357471",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 14,
    "trade_volume_24h_btc": 2511.2971010682036,
    "trade_volume_24h_btc_normalized": 1360.8887630500656
  },
  {
    "id": "gemini",
    "name": "Gemini",
    "year_established": 2014,
    "country": "United States",
    "description": "",
    "url": "https://www.gemini.com/exchange",
    "image": "https://assets.coingecko.com/markets/images/50/small/gemini.png?1605704107",
    "has_trading_incentive": false,
    "trust_score": 9,
    "trust_score_rank": 15,
    "trade_volume_24h_btc": 469.01914624965764,
    "trade_volume_24h_btc_normalized": 469.01914624965764
  },
  {
    "id": "whitebit",
    "name": "WhiteBIT",
    "year_established": 2018,
    "country": "Lithuania",
    "description": "",
    "url": "https://whitebit.com",
    "image": "https://assets.coingecko.com/markets/images/418/small/whitebit_final.png?1667923522",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 16,
    "trade_volume_24h_btc": 17736.67499907916,
    "trade_volume_24h_btc_normalized": 17736.67499907916
  },
  {
    "id": "bitget",
    "name": "Bitget",
    "year_established": 2018,
    "country": "Seychelles",
    "description": "",
    "url": "https://www.bitget.com/",
    "image": "https://assets.coingecko.com/markets/images/540/small/Bitget_new_logo_2.png?1630049618",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 17,
    "trade_volume_24h_btc": 31216.357904197128,
    "trade_volume_24h_btc_normalized": 17647.07050850834
  },
  {
    "id": "upbit",
    "name": "Upbit",
    "year_established": 2017,
    "country": "South Korea",
    "description": "",
    "url": "https://upbit.com",
    "image": "https://assets.coingecko.com/markets/images/117/small/upbit.png?1520388800",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 18,
    "trade_volume_24h_btc": 29396.22546818111,
    "trade_volume_24h_btc_normalized": 11064.875927711582
  },
  {
    "id": "bitmart",
    "name": "BitMart",
    "year_established": 2017,
    "country": "Cayman Islands",
    "description": "",
    "url": "https://www.bitmart.com/en",
    "image": "https://assets.coingecko.com/markets/images/239/small/Bitmart.png?1628066397",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 19,
    "trade_volume_24h_btc": 11973.278111007276,
    "trade_volume_24h_btc_normalized": 9682.661547614067
  },
  {
    "id": "btse",
    "name": "BTSE",
    "year_established": 2018,
    "country": "British Virgin Islands",
    "description": "BTSE is a leading digital asset exchange that empowers users by offering a simple and secure way to trade. Its growing suite of financial services is designed to bridge traditional finance with digital assets solutions. BTSE's innovative technology offers a set of digital financial solutions featuring multi-currency spot and derivatives trading, in addition to NFT and exchange white labels, over-the-counter (OTC) trading, asset management, and payment gateways. Additionally, BTSE provides an all-in-one order book, strict security protocols, an insurance fund, cold storage for more than 99% of assets and no withdrawal limits on over 12 fiat currencies and 100 cryptocurrencies.",
    "url": "https://www.btse.com/",
    "image": "https://assets.coingecko.com/markets/images/464/small/BTSE.jpg?1568012415",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 20,
    "trade_volume_24h_btc": 12276.324676012071,
    "trade_volume_24h_btc_normalized": 6567.315455596661
  },
  {
    "id": "exmo",
    "name": "EXMO",
    "year_established": 2013,
    "country": "United Kingdom",
    "description": "",
    "url": "https://exmo.com/",
    "image": "https://assets.coingecko.com/markets/images/59/small/tt_ava.jpg?1669360697",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 21,
    "trade_volume_24h_btc": 2670.9783466666963,
    "trade_volume_24h_btc_normalized": 2670.9783466666963
  },
  {
    "id": "coinex",
    "name": "CoinEx",
    "year_established": 2017,
    "country": "Samoa",
    "description": "",
    "url": "https://www.coinex.com/",
    "image": "https://assets.coingecko.com/markets/images/135/small/coinex.jpg?1527737297",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 22,
    "trade_volume_24h_btc": 1789.6822743152716,
    "trade_volume_24h_btc_normalized": 1789.6822743152716
  },
  {
    "id": "bitbank",
    "name": "Bitbank",
    "year_established": 2016,
    "country": "Japan",
    "description": "",
    "url": "https://bitbank.cc/",
    "image": "https://assets.coingecko.com/markets/images/122/small/bitbank.jpg?1521186278",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 23,
    "trade_volume_24h_btc": 553.7262278784248,
    "trade_volume_24h_btc_normalized": 553.7262278784248
  },
  {
    "id": "latoken",
    "name": "LATOKEN",
    "year_established": 2017,
    "country": "Cayman Islands",
    "description": "",
    "url": "https://latoken.com/",
    "image": "https://assets.coingecko.com/markets/images/124/small/latoken.png?1685942070",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 24,
    "trade_volume_24h_btc": 4933.412917708617,
    "trade_volume_24h_btc_normalized": 505.3483019119227
  },
  {
    "id": "bitso",
    "name": "Bitso",
    "year_established": 2014,
    "country": "Gibraltar",
    "description": "",
    "url": "https://bitso.com",
    "image": "https://assets.coingecko.com/markets/images/8/small/Bitso-icon-dark.png?1581909156",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 25,
    "trade_volume_24h_btc": 372.77750344138497,
    "trade_volume_24h_btc_normalized": 372.77750344138497
  },
  {
    "id": "wootrade",
    "name": "WOO X",
    "year_established": 2019,
    "country": "Seychelles",
    "description": "WOO Network is a deep liquidity network connecting traders, exchanges, institutions, and DeFi platforms with democratized access to the best-in-class liquidity and trading execution at lower or zero cost. Its flagship, WOO X, is a professional trading platform featuring customizable modules and lower to zero fees complete with deep liquidity. WOO Network was founded by Kronos Research, a quantitative trading firm generating $5-10B in daily volume.",
    "url": "https://woo.org/",
    "image": "https://assets.coingecko.com/markets/images/683/small/woo.png?1677468948",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 26,
    "trade_volume_24h_btc": 948.3192713409204,
    "trade_volume_24h_btc_normalized": 334.26761535777945
  },
  {
    "id": "valr",
    "name": "VALR",
    "year_established": 2018,
    "country": "South Africa",
    "description": "",
    "url": "https://www.valr.com/",
    "image": "https://assets.coingecko.com/markets/images/1036/small/valr.png?1674711237",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 27,
    "trade_volume_24h_btc": 171.56877433913587,
    "trade_volume_24h_btc_normalized": 148.42173730229766
  },
  {
    "id": "coinspro",
    "name": "Coins.ph",
    "year_established": null,
    "country": "Philippines",
    "description": "",
    "url": "https://coins.ph/about",
    "image": "https://assets.coingecko.com/markets/images/999/small/coinspro.png?1668488887",
    "has_trading_incentive": false,
    "trust_score": 8,
    "trust_score_rank": 28,
    "trade_volume_24h_btc": 21.17689455823163,
    "trade_volume_24h_btc_normalized": 21.17689455823163
  },
  {
    "id": "digifinex",
    "name": "DigiFinex",
    "year_established": 2018,
    "country": "Seychelles",
    "description": "",
    "url": "https://www.digifinex.com/",
    "image": "https://assets.coingecko.com/markets/images/225/small/DF_logo.png?1594264355",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 29,
    "trade_volume_24h_btc": 25519.725893460592,
    "trade_volume_24h_btc_normalized": 23555.484289512893
  },
  {
    "id": "xt",
    "name": "XT.COM",
    "year_established": 2018,
    "country": "Seychelles",
    "description": "By consistently expanding its ecosystem, XT.COM is dedicated to providing users with the most secure, trusted, and hassle-free digital asset trading services. Our exchange is built from a desire to give everyone access to digital assets regardless where you are. \r\n\r\nFounded in 2018, XT.COM now serves more than 6 million registered users, over 500,000+ monthly active users and 40+ million users in the ecosystem. Covering a rich variety of  trading categories together with a NFT aggregated marketplace,  our platform strives to cater to its large user base by providing a secure, trusted and intuitive trading experience.\r\n\r\nAs the world’s first social-infused digital assets trading platform, XT.COM also supports social networking platform based transactions to make our crypto services more accessible to users all over the world. Furthermore, to ensure optimal data integrity and security, we see user security as our top priority at XT.COM. ",
    "url": "https://www.xt.com/",
    "image": "https://assets.coingecko.com/markets/images/404/small/logo400x400.png?1575881839",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 30,
    "trade_volume_24h_btc": 17328.96735904751,
    "trade_volume_24h_btc_normalized": 10176.048350800867
  },
  {
    "id": "coinsbit",
    "name": "Coinsbit",
    "year_established": null,
    "country": "Estonia",
    "description": "",
    "url": "https://coinsbit.io/",
    "image": "https://assets.coingecko.com/markets/images/267/small/Coinsbit.png?1605153697",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 31,
    "trade_volume_24h_btc": 9769.9484699528,
    "trade_volume_24h_btc_normalized": 9769.9484699528
  },
  {
    "id": "btcex",
    "name": "BTCEX",
    "year_established": 2021,
    "country": "Seychelles",
    "description": "BTCEX is a highly extensible digital asset trading platform, which provides spot, spot leverage, futures, perpetual contracts, and USDT-settled options. In addition, it also supports multi-product portfolio margin models to improve the utilization of user funds.",
    "url": "https://www.btcex.com",
    "image": "https://assets.coingecko.com/markets/images/753/small/C8tiQdwL_400x400.jpg?1641348961",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 32,
    "trade_volume_24h_btc": 16432.31152584994,
    "trade_volume_24h_btc_normalized": 7798.65236529025
  },
  {
    "id": "tidex",
    "name": "Tidex",
    "year_established": 2017,
    "country": "Lithuania",
    "description": "",
    "url": "https://tidex.com/",
    "image": "https://assets.coingecko.com/markets/images/43/small/favicon.png?1651817092",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 33,
    "trade_volume_24h_btc": 10758.838061487319,
    "trade_volume_24h_btc_normalized": 4921.376895408138
  },
  {
    "id": "bithumb",
    "name": "Bithumb",
    "year_established": 2014,
    "country": "South Korea",
    "description": "",
    "url": "https://www.bithumb.com/",
    "image": "https://assets.coingecko.com/markets/images/6/small/bithumb_BI.png?1573104549",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 34,
    "trade_volume_24h_btc": 5583.263210967619,
    "trade_volume_24h_btc_normalized": 4382.210300344296
  },
  {
    "id": "bitrue",
    "name": "Bitrue",
    "year_established": 2018,
    "country": "Singapore",
    "description": "",
    "url": "https://www.bitrue.com/",
    "image": "https://assets.coingecko.com/markets/images/254/small/unnamed_%281%29.png?1656295820",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 35,
    "trade_volume_24h_btc": 30664.003455737708,
    "trade_volume_24h_btc_normalized": 4159.707024535387
  },
  {
    "id": "bigone",
    "name": "BigONE",
    "year_established": 2017,
    "country": "Netherlands",
    "description": "",
    "url": "https://bigone.com",
    "image": "https://assets.coingecko.com/markets/images/100/small/qcFFufEY_400x400.jpg?1561103345",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 36,
    "trade_volume_24h_btc": 3482.9076921413644,
    "trade_volume_24h_btc_normalized": 3482.9076921413644
  },
  {
    "id": "dextrade",
    "name": "Dex-Trade",
    "year_established": 2019,
    "country": "Belize",
    "description": "Dex-Trade is a centralized cryptocurrency exchange founded in 2017 and registered in Belize. This is a modern space for safe and comfortable trading with minimal commissions.\r\n\r\nDex-Trade is a universal exchange for both beginners and professional traders. The minimum spread and high liquidity in order books allow you to trade efficiently with orders of any volume.\r\nAlong with global opportunities, the exchange also provides a demo trading mode for risk-free testing of your trading strategies. Our dedicated support team is online 24/7 to assist you with any questions.\r\n\r\nYou can learn more about Dex-Trade on the website.\r\nhttps://dex-trade.com/info/about\r\n\r\nIf you are looking for listing and promotion options with Dex-Trade please visit our listing page and a personal manager will help you to utilize our proven tools and intelligent market-making system to engage with the vast exchange community in the best possible way. https://dex-trade.com/listing",
    "url": "https://dex-trade.com/",
    "image": "https://assets.coingecko.com/markets/images/380/small/Dex-Trade_logo_new.png?1599629803",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 37,
    "trade_volume_24h_btc": 3173.8441384801513,
    "trade_volume_24h_btc_normalized": 3173.8441384801513
  },
  {
    "id": "bitmax",
    "name": "AscendEX (BitMax)",
    "year_established": 2018,
    "country": "Singapore",
    "description": "AscendEX (formerly BitMax) is a leading global digital asset financial platform founded by a group of Wall Street quantitative trading veterans in 2018, building on core value of “Efficiency, Resilience and Transparency.” \r\n \r\nDriven by its continuous innovative product development and early-mover advantage in strategic alignment with the leading projects from DeFi ecosystem, AscendEX offers trading services across over 200 trading pairs across cash, margin, and futures products, in particular margin trading of over 50 tokens in cross-asset collateral mode and futures trading in both cross-asset and isolated margin modes.",
    "url": "https://ascendex.com/en/global-digital-asset-platform",
    "image": "https://assets.coingecko.com/markets/images/277/small/%E5%8E%9F%E8%89%B2.png?1650557355",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 38,
    "trade_volume_24h_btc": 9835.21586035263,
    "trade_volume_24h_btc_normalized": 2024.4709571587628
  },
  {
    "id": "poloniex",
    "name": "Poloniex",
    "year_established": 2014,
    "country": "Seychelles",
    "description": "Poloniex was founded in January 2014 as a global cryptocurrency exchange. It provides spot trading, futures trading, staking, and various services to users in nearly 100 countries and regions with various languages available.\r\n\r\nIn 2022, Poloniex launched a brand new trading system to provide global retail and professional users with higher speed, as well as better stability and usability.",
    "url": "https://poloniex.com/",
    "image": "https://assets.coingecko.com/markets/images/37/small/poloniex.png?1663310089",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 39,
    "trade_volume_24h_btc": 1796.7431191598735,
    "trade_volume_24h_btc_normalized": 1796.7431191598735
  },
  {
    "id": "paribu",
    "name": "Paribu",
    "year_established": null,
    "country": "Turkey",
    "description": null,
    "url": "https://www.paribu.com/",
    "image": "https://assets.coingecko.com/markets/images/136/small/paribu.jpg?1527734779",
    "has_trading_incentive": null,
    "trust_score": 7,
    "trust_score_rank": 40,
    "trade_volume_24h_btc": 1765.4477680729804,
    "trade_volume_24h_btc_normalized": 1765.4477680729804
  },
  {
    "id": "bitstamp",
    "name": "Bitstamp",
    "year_established": 2013,
    "country": "Luxembourg",
    "description": "",
    "url": "https://links.bitstamp.net/c/2223866/1100037/14006",
    "image": "https://assets.coingecko.com/markets/images/9/small/bitstamp.jpg?1519627979",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 41,
    "trade_volume_24h_btc": 3865.123549921859,
    "trade_volume_24h_btc_normalized": 1736.231016455051
  },
  {
    "id": "bitflyer",
    "name": "bitFlyer",
    "year_established": 2014,
    "country": "Japan",
    "description": "",
    "url": "https://bitflyereuropesa.pxf.io/c/2223866/858437/11990",
    "image": "https://assets.coingecko.com/markets/images/5/small/bitFlyer-logo.png?1643256033",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 42,
    "trade_volume_24h_btc": 1482.6810600131928,
    "trade_volume_24h_btc_normalized": 1482.6810600131928
  },
  {
    "id": "btcturk",
    "name": "BtcTurk PRO",
    "year_established": 2013,
    "country": "Turkey",
    "description": "",
    "url": "https://pro.btcturk.com/",
    "image": "https://assets.coingecko.com/markets/images/223/small/BTCTurk-exchange.jpg?1536726120",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 43,
    "trade_volume_24h_btc": 2674.908231020776,
    "trade_volume_24h_btc_normalized": 1290.5778141145463
  },
  {
    "id": "qmall",
    "name": "QMall",
    "year_established": null,
    "country": "Lithuania",
    "description": "",
    "url": "https://qmall.io/",
    "image": "https://assets.coingecko.com/markets/images/1108/small/qmall.jpeg?1680079189",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 44,
    "trade_volume_24h_btc": 2081.597569430201,
    "trade_volume_24h_btc_normalized": 1252.1421268737315
  },
  {
    "id": "cryptology",
    "name": "Cryptology",
    "year_established": 2018,
    "country": "Lithuania",
    "description": "",
    "url": "https://cryptology.com/",
    "image": "https://assets.coingecko.com/markets/images/287/small/logo-symbol.png?1669975181",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 45,
    "trade_volume_24h_btc": 1126.8409903607421,
    "trade_volume_24h_btc_normalized": 1051.917508105945
  },
  {
    "id": "c_patex",
    "name": "C-Patex",
    "year_established": null,
    "country": "Argentina",
    "description": "",
    "url": "https://c-patex.com/",
    "image": "https://assets.coingecko.com/markets/images/246/small/Exchange.jpg?1681192003",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 46,
    "trade_volume_24h_btc": 638.7363034092706,
    "trade_volume_24h_btc_normalized": 638.7363034092706
  },
  {
    "id": "bitkub",
    "name": "Bitkub",
    "year_established": 2018,
    "country": "Thailand",
    "description": "",
    "url": "https://www.bitkub.com",
    "image": "https://assets.coingecko.com/markets/images/249/small/bitkub.png?1537180687",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 47,
    "trade_volume_24h_btc": 607.097215526117,
    "trade_volume_24h_btc_normalized": 607.097215526117
  },
  {
    "id": "max_maicoin",
    "name": "Max Maicoin",
    "year_established": null,
    "country": "Taiwan",
    "description": "",
    "url": "https://max.maicoin.com",
    "image": "https://assets.coingecko.com/markets/images/218/small/max.jpg?1533888641",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 48,
    "trade_volume_24h_btc": 567.1328846144625,
    "trade_volume_24h_btc_normalized": 567.1328846144625
  },
  {
    "id": "luno",
    "name": "Luno",
    "year_established": 2013,
    "country": "Singapore",
    "description": "",
    "url": "https://www.luno.com",
    "image": "https://assets.coingecko.com/markets/images/33/small/luno.jpg?1519996997",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 49,
    "trade_volume_24h_btc": 268.54359619221697,
    "trade_volume_24h_btc_normalized": 268.54359619221697
  },
  {
    "id": "indodax",
    "name": "Indodax",
    "year_established": 2014,
    "country": "Indonesia",
    "description": "",
    "url": "https://indodax.com",
    "image": "https://assets.coingecko.com/markets/images/3/small/logogram-Indodax-new-_JPG_format.jpg?1580974378",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 50,
    "trade_volume_24h_btc": 197.74965788187205,
    "trade_volume_24h_btc_normalized": 197.74965788187205
  },
  {
    "id": "btcmarkets",
    "name": "BTCMarkets",
    "year_established": null,
    "country": "Australia",
    "description": "",
    "url": "https://www.btcmarkets.net/",
    "image": "https://assets.coingecko.com/markets/images/237/small/BTCMarkets_logo2.png?1677732205",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 51,
    "trade_volume_24h_btc": 194.86928117901883,
    "trade_volume_24h_btc_normalized": 194.86928117901883
  },
  {
    "id": "cex",
    "name": "CEX.IO",
    "year_established": 2013,
    "country": "United Kingdom",
    "description": "",
    "url": "https://cex.io/",
    "image": "https://assets.coingecko.com/markets/images/56/small/main-icon.png?1617267530",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 52,
    "trade_volume_24h_btc": 150.61181800616583,
    "trade_volume_24h_btc_normalized": 150.61181800616583
  },
  {
    "id": "bittrex",
    "name": "Bittrex Global",
    "year_established": 2014,
    "country": "Liechtenstein",
    "description": "Bittrex Global is a centralised cryptocurrency exchange. Established in 2014, it is registered with the Financial Market Authority in Liechtenstein, regulated by the Bermuda Monetary Authority, and licensed under the Bermuda Digital Asset Business Act 2018 to operate as a digital asset exchange, provide custodial wallet services and operate as a digital asset exchange provider.",
    "url": "https://global.bittrex.com",
    "image": "https://assets.coingecko.com/markets/images/10/small/BG-color-250x250_icon.png?1596167574",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 53,
    "trade_volume_24h_btc": 74.89770663206117,
    "trade_volume_24h_btc_normalized": 74.89770663206117
  },
  {
    "id": "blockchain_com",
    "name": "Blockchain.com",
    "year_established": 2012,
    "country": "United Kingdom",
    "description": "",
    "url": "https://www.blockchain.com/",
    "image": "https://assets.coingecko.com/markets/images/613/small/unnamedddd.png?1610503741",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 54,
    "trade_volume_24h_btc": 56.93572164964927,
    "trade_volume_24h_btc_normalized": 56.93572164964927
  },
  {
    "id": "bitpanda",
    "name": "Bitpanda Pro",
    "year_established": 2019,
    "country": "Austria",
    "description": "",
    "url": "https://exchange.bitpanda.com",
    "image": "https://assets.coingecko.com/markets/images/474/small/appicon-ios-pro.png?1622626638",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 55,
    "trade_volume_24h_btc": 24.478922234222118,
    "trade_volume_24h_btc_normalized": 24.478922234222118
  },
  {
    "id": "coin_metro",
    "name": "Coinmetro",
    "year_established": 2018,
    "country": "Estonia",
    "description": "",
    "url": "https://coinmetro.com/",
    "image": "https://assets.coingecko.com/markets/images/386/small/Coinmetro_Exchange_Logo_%282%29.png?1646280101",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 56,
    "trade_volume_24h_btc": 18.971806898401983,
    "trade_volume_24h_btc_normalized": 18.971806898401983
  },
  {
    "id": "delta_spot",
    "name": "Delta Exchange",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://www.delta.exchange/app/spot/trade/",
    "image": "https://assets.coingecko.com/markets/images/642/small/delta_spot.jpg?1617283005",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 57,
    "trade_volume_24h_btc": 17.70450822952537,
    "trade_volume_24h_btc_normalized": 17.70450822952537
  },
  {
    "id": "bitmex_spot",
    "name": "BitMEX",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://www.bitmex.com/spot/",
    "image": "https://assets.coingecko.com/markets/images/866/small/bitmex.jpeg?1652794708",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 58,
    "trade_volume_24h_btc": 10.770342076479583,
    "trade_volume_24h_btc_normalized": 10.770342076479583
  },
  {
    "id": "kuna",
    "name": "Kuna Exchange",
    "year_established": null,
    "country": "United Kingdom",
    "description": "",
    "url": "https://kuna.io/",
    "image": "https://assets.coingecko.com/markets/images/97/small/kuna_exchange.png?1545126178",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 59,
    "trade_volume_24h_btc": 9.235769169873302,
    "trade_volume_24h_btc_normalized": 9.235769169873302
  },
  {
    "id": "okcoin",
    "name": "Okcoin",
    "year_established": 2013,
    "country": "United States",
    "description": "Founded in 2013, Okcoin is a US-headquartered cryptocurrency exchange serving 190+ countries and territories. The platform enables retail and institutional investors to purchase digital assets using local currencies, with a mission to make crypto easy for everyone, including first-time buyers. Okcoin was the first centralized exchange to offer direct entry into decentralized finance (DeFi) with Earn, a tool for earning APY through decentralized lending, liquidity pools, staking, and more. In addition, Okcoin offers institutional trading tools and APIs to asset managers, venture capital and hedge funds, retail brokers, payment processors, and more. Follow Okcoin on Twitter at @Okcoin and visit okcoin.com for more information.",
    "url": "https://www.okcoin.com/",
    "image": "https://assets.coingecko.com/markets/images/415/small/okcoin_Logomark_SatoshiBlack.png?1619574335",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 60,
    "trade_volume_24h_btc": 2.0192247008081385,
    "trade_volume_24h_btc_normalized": 2.0192247008081385
  },
  {
    "id": "lbank",
    "name": "LBank",
    "year_established": 2015,
    "country": "British Virgin Islands",
    "description": "LBank is a globally based centralized exchange (CEX) platform established in 2015. The platform allows users to buy and sell major crypto assets like Bitcoin (BTC) and Ethereum (ETH) in over 149 fiat currencies, with over 20 payment methods. The company has licenses from the National Futures Association, Italian Organismo degli Agenti e dei Mediatori, and money services businesses in the United States & Canada. The LBank exchange has over 9 million users and accepts clients from over 200 regions.\r\nLBank Exchange provides its users with crypto trading, specialized financial derivatives, and professional asset management services.\r\n ",
    "url": "https://www.lbank.com",
    "image": "https://assets.coingecko.com/markets/images/118/small/LBank_logo.png?1666234663",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 61,
    "trade_volume_24h_btc": 24635.32039531671,
    "trade_volume_24h_btc_normalized": 15219.386651796809
  },
  {
    "id": "uniswap_v3_arbitrum",
    "name": "Uniswap V3 (Arbitrum One)",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://app.uniswap.org/#/swap",
    "image": "https://assets.coingecko.com/markets/images/702/small/uniswap-v3.png?1631616149",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 62,
    "trade_volume_24h_btc": 7904.814827325668,
    "trade_volume_24h_btc_normalized": 7904.814827325668
  },
  {
    "id": "toobit",
    "name": "Toobit",
    "year_established": null,
    "country": "Cayman Islands",
    "description": "",
    "url": "https://www.toobit.com/",
    "image": "https://assets.coingecko.com/markets/images/1139/small/Toobit_logo400X400.png?1686549566",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 63,
    "trade_volume_24h_btc": 12170.95186764092,
    "trade_volume_24h_btc_normalized": 7280.678977840162
  },
  {
    "id": "bitforex",
    "name": "Bitforex",
    "year_established": 2018,
    "country": "Seychelles",
    "description": "",
    "url": "https://www.bitforex.com/",
    "image": "https://assets.coingecko.com/markets/images/214/small/BitForex-Logo.png?1573808227",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 64,
    "trade_volume_24h_btc": 74287.27379148253,
    "trade_volume_24h_btc_normalized": 6984.152670018598
  },
  {
    "id": "p2pb2b",
    "name": "P2B",
    "year_established": 2018,
    "country": "Lithuania",
    "description": "P2B Cryptocurrency Exchange is one of the biggest European digital assets exchanges that has successfully operated for over 5 years. It is now the most trusted platform offering the best go-to-market experience for crypto users and projects.\r\n\r\nThe platform tops the most trusted ratings worldwide - CoinGecko - and permanently improves its position. We assure the safety of the trading activities, being ranked in the TOP-12 in Cer.Live security rate. \r\n\r\nThe users can easily explore the mature crypto market by investing in a wide variety of liquid tokens, buying cryptocurrencies with bank cards (via Simplex, Moon Pay, Koinal) and using attractive discounts or bonuses during fundraising campaigns. You can also choose the amount of your commission,  - use the level commission to raise your account opportunities and make your trading more profitable. \r\n\r\nBecome a part of the prosperous P2B community - #1 place to be in crypto.\r\nGet your exciting trading experience with 24/7 support, and gain quickly and securely.\r\n",
    "url": "https://p2pb2b.com/",
    "image": "https://assets.coingecko.com/markets/images/251/small/ow0xng56_400x400.jpeg?1664939403",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 65,
    "trade_volume_24h_btc": 14136.232934844851,
    "trade_volume_24h_btc_normalized": 5930.079659503698
  },
  {
    "id": "pancakeswap-v3-bsc",
    "name": "Pancakeswap V3 (BSC)",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://pancakeswap.finance/swap",
    "image": "https://assets.coingecko.com/markets/images/1111/small/pancakeswap.jpeg?1680396625",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 66,
    "trade_volume_24h_btc": 5212.656661601107,
    "trade_volume_24h_btc_normalized": 5212.656661601107
  },
  {
    "id": "difx",
    "name": "DIFX",
    "year_established": 2021,
    "country": "Cayman Islands",
    "description": "",
    "url": "https://difx.com/en",
    "image": "https://assets.coingecko.com/markets/images/1138/small/difx.png?1683531591",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 67,
    "trade_volume_24h_btc": 6891.863176381249,
    "trade_volume_24h_btc_normalized": 2705.8991715690254
  },
  {
    "id": "coinstore",
    "name": "Coinstore",
    "year_established": 2020,
    "country": "Singapore",
    "description": "Coinstore: A Global Cryptocurrency Exchange Revolutionizing Crypto Finance\r\n\r\nCoinstore is a leading global cryptocurrency exchange that brings together a team of seasoned financial professionals and blockchain experts. With a strong presence in 175 countries and a user base of 3.3 million registered traders, Coinstore offers seamless and rapid trading services, along with derivatives, OTC, and NFT solutions.\r\n\r\nWhat sets Coinstore apart is its exceptional trading speed, operating at millisecond-level precision. The platform boasts a robust server architecture, ensuring smooth and efficient transactions for users worldwide. Security is a top priority, with Coinstore implementing bank-level measures to safeguard user assets. A comprehensive risk control system and real-time reconciliation further enhance the peace of mind for traders.\r\n\r\nCoinstore's dedication to excellence has been recognized within the industry. It has been crowned the best exchange in Asia by Crypto 306, while also earning the esteemed title of best rising star from Crypto Expo. This recognition highlights Coinstore's commitment to revolutionize the world of crypto finance.\r\n\r\nDiscover the future of cryptocurrency trading and financial innovation with Coinstore.com. Join our ever-growing community and experience the cutting-edge solutions that are reshaping the crypto landscape.\r\n\r\n",
    "url": "https://www.coinstore.com/#/",
    "image": "https://assets.coingecko.com/markets/images/747/small/coinstore.jpeg?1639530357",
    "has_trading_incentive": false,
    "trust_score": 7,
    "trust_score_rank": 68,
    "trade_volume_24h_btc": 10732.696980237024,
    "trade_volume_24h_btc_normalized": 2642.354960553045
  },
  {
    "id": "uniswap_v3_polygon_pos",
    "name": "Uniswap V3 (Polygon)",
    "year_established": 2021,
    "country": null,
    "description": "",
    "url": "https://app.uniswap.org/#/swap",
    "image": "https://assets.coingecko.com/markets/images/752/small/uniswap-polygon.png?1640329417",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 69,
    "trade_volume_24h_btc": 2506.413664749313,
    "trade_volume_24h_btc_normalized": 2506.413664749313
  },
  {
    "id": "pancakeswap_new",
    "name": "PancakeSwap (v2)",
    "year_established": 2020,
    "country": null,
    "description": "",
    "url": "https://pancakeswap.finance",
    "image": "https://assets.coingecko.com/markets/images/687/small/pancakeswap.jpeg?1626060212",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 70,
    "trade_volume_24h_btc": 1639.1814114494252,
    "trade_volume_24h_btc_normalized": 1639.1814114494252
  },
  {
    "id": "uniswap_v2",
    "name": "Uniswap V2 (Ethereum)",
    "year_established": 2018,
    "country": null,
    "description": "",
    "url": "https://app.uniswap.org/#/swap?use=V2",
    "image": "https://assets.coingecko.com/markets/images/535/small/256x256_Black-1.png?1590893262",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 71,
    "trade_volume_24h_btc": 1538.3042444607697,
    "trade_volume_24h_btc_normalized": 1538.3042444607697
  },
  {
    "id": "bitvavo",
    "name": "Bitvavo",
    "year_established": 2018,
    "country": "Netherlands",
    "description": "",
    "url": "https://bitvavo.com/en",
    "image": "https://assets.coingecko.com/markets/images/714/small/bitvavo-mark-square-black.png?1633688872",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 72,
    "trade_volume_24h_btc": 1189.5367250786283,
    "trade_volume_24h_btc_normalized": 1189.5367250786283
  },
  {
    "id": "bitcoin_com",
    "name": "FMFW.io",
    "year_established": 2019,
    "country": "Bahamas",
    "description": "The mission of FMFW.io is to empower people from all over the world to trade cryptocurrencies with ease and confidence, from first-time traders to advanced trading professionals. With high liquidity, 24/7 multilingual support and dozens of trading pairs, complemented with a high level of security, we offer an attractive platform for trading any cryptocurrency. Within one year since launch, on average, our exchange has been visited by more than 500K active traders per month, and this number continues to grow as you read this sentence. \r\n\r\nKey Features:\r\n\r\n- Enjoy more than 130 available trading pairs\r\n- Cutting-edge matching engine technologies\r\n- Up 5x and 10x leverage for more than 29 markets\r\n- Deep liquidity\r\n- User-friendly trading terminal\r\n- Tight spreads\r\n- Consistent trading competitions and giveaways",
    "url": "https://fmfw.io/",
    "image": "https://assets.coingecko.com/markets/images/467/small/fmfw.png?1635491491",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 73,
    "trade_volume_24h_btc": 9378.688839463313,
    "trade_volume_24h_btc_normalized": 723.8762154208885
  },
  {
    "id": "uniswap_v3_optimism",
    "name": "Uniswap V3 (Optimism)",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://app.uniswap.org/#/swap",
    "image": "https://assets.coingecko.com/markets/images/725/small/uniswap-v3.png?1634896204",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 74,
    "trade_volume_24h_btc": 664.0896226043478,
    "trade_volume_24h_btc_normalized": 664.0896226043478
  },
  {
    "id": "pointpay",
    "name": "PointPay",
    "year_established": 2018,
    "country": "Saint Vincent and the Grenadines",
    "description": "",
    "url": "https://exchange.pointpay.io/",
    "image": "https://assets.coingecko.com/markets/images/1060/small/pointpay.png?1676882506",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 75,
    "trade_volume_24h_btc": 1304.5456922487137,
    "trade_volume_24h_btc_normalized": 647.0525699211714
  },
  {
    "id": "syncswap",
    "name": "SyncSwap",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://syncswap.xyz/swap",
    "image": "https://assets.coingecko.com/markets/images/1113/small/kg4-p_V7_400x400.jpg?1680752024",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 76,
    "trade_volume_24h_btc": 508.9347080642546,
    "trade_volume_24h_btc_normalized": 508.9347080642546
  },
  {
    "id": "dodo_bsc",
    "name": "Dodo (BSC)",
    "year_established": 2021,
    "country": null,
    "description": "",
    "url": "https://dodoex.io/",
    "image": "https://assets.coingecko.com/markets/images/640/small/41tgsq69_400x400.png?1618372654",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 77,
    "trade_volume_24h_btc": 491.431509046789,
    "trade_volume_24h_btc_normalized": 491.431509046789
  },
  {
    "id": "orca",
    "name": "Orca",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://www.orca.so/",
    "image": "https://assets.coingecko.com/markets/images/691/small/orca.png?1628047248",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 78,
    "trade_volume_24h_btc": 457.75801273451907,
    "trade_volume_24h_btc_normalized": 363.59322563160583
  },
  {
    "id": "gmo_japan",
    "name": "GMO Japan",
    "year_established": null,
    "country": "Japan",
    "description": "",
    "url": "https://coin.z.com/jp/",
    "image": "https://assets.coingecko.com/markets/images/430/small/gmo_z_com.png?1561112572",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 79,
    "trade_volume_24h_btc": 351.11997454258676,
    "trade_volume_24h_btc_normalized": 351.11997454258676
  },
  {
    "id": "kanga",
    "name": "Kanga",
    "year_established": 2018,
    "country": "Belize",
    "description": "",
    "url": "https://kanga.exchange/",
    "image": "https://assets.coingecko.com/markets/images/852/small/KaNGa_logo.png?1681790128",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 80,
    "trade_volume_24h_btc": 326.4484571529244,
    "trade_volume_24h_btc_normalized": 326.4484571529244
  },
  {
    "id": "velodrome",
    "name": "Velodrome Finance",
    "year_established": 2022,
    "country": null,
    "description": "Velodrome Finance, at its core, is a solution for protocols on Optimism to properly incentivize liquidity for their own use cases. Building on top of the groundwork laid out by Solidly, our team has addressed that first iteration's core issues to realize its full potential.\r\n\r\nThe team behind Velodrome Finance previously launched veDAO, an initiative incubated by Information Token. veDAO's founding mandate was to engage with the Solidly ecosystem, a protocol launched on the Fantom network by Andre Cronje, while driving long-term value to the veDAO community.\r\n\r\nThe veDAO team has since developed deep subject matter expertise on both Solidly, the veNFT primitive, and the ve(3,3) mechanism, becoming the go-to resource for protocols and chains seeking support around these topics.",
    "url": "https://app.velodrome.finance/swap",
    "image": "https://assets.coingecko.com/markets/images/933/small/velodrome-finance.png?1660261754",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 81,
    "trade_volume_24h_btc": 309.3947443653912,
    "trade_volume_24h_btc_normalized": 309.3947443653912
  },
  {
    "id": "independent_reserve",
    "name": "Independent Reserve",
    "year_established": 2013,
    "country": "Australia",
    "description": "",
    "url": "https://www.independentreserve.com/",
    "image": "https://assets.coingecko.com/markets/images/389/small/x_V5Jquo_400x400.png?1556071437",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 82,
    "trade_volume_24h_btc": 703.7766473046029,
    "trade_volume_24h_btc_normalized": 249.46707130035256
  },
  {
    "id": "bitazza",
    "name": "Bitazza",
    "year_established": 2021,
    "country": null,
    "description": "Bitazza is ASEAN's locally-based digital asset platform. ",
    "url": "https://trade.bitazza.com/gl/exchange/",
    "image": "https://assets.coingecko.com/markets/images/837/small/btzlogo200x200_darkgreen.png?1648702264",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 83,
    "trade_volume_24h_btc": 244.43142770157053,
    "trade_volume_24h_btc_normalized": 244.43142770157053
  },
  {
    "id": "pancakeswap-v3-ethereum",
    "name": "Pancakeswap V3 (Ethereum)",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://pancakeswap.finance/swap",
    "image": "https://assets.coingecko.com/markets/images/1112/small/pancakeswap.jpeg?1680397048",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 84,
    "trade_volume_24h_btc": 245.5105685772845,
    "trade_volume_24h_btc_normalized": 245.5105685772845
  },
  {
    "id": "thena-fusion",
    "name": "THENA FUSION",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://www.thena.fi/swap",
    "image": "https://assets.coingecko.com/markets/images/1123/small/thena.jpeg?1681986498",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 85,
    "trade_volume_24h_btc": 233.57816799582818,
    "trade_volume_24h_btc_normalized": 233.57816799582818
  },
  {
    "id": "sushiswap",
    "name": "Sushiswap",
    "year_established": 2020,
    "country": null,
    "description": "",
    "url": "https://app.sushi.com/swap",
    "image": "https://assets.coingecko.com/markets/images/576/small/2048x2048_Logo.png?1609208464",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 86,
    "trade_volume_24h_btc": 210.60213369240714,
    "trade_volume_24h_btc_normalized": 210.60213369240714
  },
  {
    "id": "osmosis",
    "name": "Osmosis",
    "year_established": 2021,
    "country": null,
    "description": "Osmosis is an automated market maker (AMM) protocol built for liquidity providers. It is built based on the Cosmos SDK and is the first dex for IBC tokens.",
    "url": "https://app.osmosis.zone/",
    "image": "https://assets.coingecko.com/markets/images/684/small/osmosis-dex.jpeg?1624850295",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 87,
    "trade_volume_24h_btc": 210.45692690096345,
    "trade_volume_24h_btc_normalized": 210.45692690096345
  },
  {
    "id": "camelot",
    "name": "Camelot",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://camelot.exchange/",
    "image": "https://assets.coingecko.com/markets/images/1007/small/vj5DIMhP_400x400.jpeg?1670561015",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 88,
    "trade_volume_24h_btc": 149.13009593547665,
    "trade_volume_24h_btc_normalized": 149.13009593547665
  },
  {
    "id": "kyberswap_elastic_polygon",
    "name": "Kyberswap Elastic (Polygon)",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://kyberswap.com/swap?networkId=137",
    "image": "https://assets.coingecko.com/markets/images/959/small/kyberswap.jpeg?1662616218",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 89,
    "trade_volume_24h_btc": 140.6412698200296,
    "trade_volume_24h_btc_normalized": 140.6412698200296
  },
  {
    "id": "bitopro",
    "name": "BitoPro",
    "year_established": 2018,
    "country": "Taiwan",
    "description": "",
    "url": "https://www.bitopro.com/",
    "image": "https://assets.coingecko.com/markets/images/358/small/bitopro_coingecko_250x250_%281%29.png?1575884378",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 90,
    "trade_volume_24h_btc": 1978.5053746649562,
    "trade_volume_24h_btc_normalized": 128.4971968206687
  },
  {
    "id": "nominex",
    "name": "Nominex",
    "year_established": 2019,
    "country": "Seychelles",
    "description": "New trading platform for convenient trading experience with low fees and numerous instruments. \r\n\r\nAbsolutely unique affiliate program that allows to earn from an infinite number of referral levels, compared to 2-3 levels at all other exchanges. \r\n\r\nA unique model for the free 2 phases distribution of the native NMX token.\r\n\r\nAdvanced Trading Instruments – using Stop, Stop Limit, Trailing Stop, Scaled and other types of orders brings some kind of trading automation without the need to develop a trading bot, which allows to easily get more profit while trading.",
    "url": "https://www.nominex.io",
    "image": "https://assets.coingecko.com/markets/images/530/small/logo-200x200.png?1587543672",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 91,
    "trade_volume_24h_btc": 323.2387367008008,
    "trade_volume_24h_btc_normalized": 128.3032016038628
  },
  {
    "id": "fastex",
    "name": "Fastex",
    "year_established": null,
    "country": "Lithuania",
    "description": "",
    "url": "https://exchange.fastex.com/",
    "image": "https://assets.coingecko.com/markets/images/1091/small/fastex.png?1678776256",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 92,
    "trade_volume_24h_btc": 100.69952699775132,
    "trade_volume_24h_btc_normalized": 100.69952699775132
  },
  {
    "id": "katana",
    "name": "Katana",
    "year_established": 2021,
    "country": null,
    "description": "",
    "url": "https://katana.roninchain.com/#/swap",
    "image": "https://assets.coingecko.com/markets/images/731/small/ronin-katana.png?1636437019",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 93,
    "trade_volume_24h_btc": 81.0266526080996,
    "trade_volume_24h_btc_normalized": 81.0266526080996
  },
  {
    "id": "pancakeswap_stableswap",
    "name": "Pancakeswap (Stableswap)",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://pancakeswap.finance/swap",
    "image": "https://assets.coingecko.com/markets/images/1035/small/pancakeswap.jpeg?1674702488",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 94,
    "trade_volume_24h_btc": 80.39367199365648,
    "trade_volume_24h_btc_normalized": 80.39367199365648
  },
  {
    "id": "korbit",
    "name": "Korbit",
    "year_established": 2013,
    "country": "South Korea",
    "description": "",
    "url": "https://www.korbit.co.kr/",
    "image": "https://assets.coingecko.com/markets/images/28/small/korbit-logo.png?1584091827",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 95,
    "trade_volume_24h_btc": 79.28736690191991,
    "trade_volume_24h_btc_normalized": 79.28736690191991
  },
  {
    "id": "kyberswap_elastic_optimism",
    "name": "Kyberswap Elastic (Optimism)",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://kyberswap.com/swap?networkId=10",
    "image": "https://assets.coingecko.com/markets/images/962/small/kyberswap.jpeg?1662695089",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 96,
    "trade_volume_24h_btc": 74.32762868111192,
    "trade_volume_24h_btc_normalized": 74.32762868111192
  },
  {
    "id": "klayswap",
    "name": "KLAYSwap",
    "year_established": null,
    "country": null,
    "description": "",
    "url": "https://klayswap.com/exchange/swap",
    "image": "https://assets.coingecko.com/markets/images/1008/small/klayswap.jpeg?1670810834",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 97,
    "trade_volume_24h_btc": 71.18472734145533,
    "trade_volume_24h_btc_normalized": 71.18472734145533
  },
  {
    "id": "coinjar",
    "name": "CoinJar Exchange",
    "year_established": 2013,
    "country": "United Kingdom",
    "description": "CoinJar is the simplest way to buy, sell and spend cryptocurrency. Founded in 2013, our mission is to create best-in-class apps and products that make cryptocurrencies such as Bitcoin and Ethereum accessible and easy-to-use for everyone, every day. CoinJar has processed billions of dollars in transactions and is used by hundreds of thousands cryptocurrency traders and investors.\r\n\r\nCoinJar is one of the first crypto exchanges in the world to be officially registered with the UK’s Financial Conduct Authority (FCA). CoinJar is also an official partner with the Premier League’s Brentford FC and Australia’s oldest football club (and 2021 champions), the Melbourne Demons.\r\n\r\nCoinJar's highly rated iOS and Android apps allow users to trade cryptocurrencies on the go, while CoinJar Exchange and CoinJar OTC Trading Desk cater for professional traders, as well as individuals and institutions looking to make larger transactions.\r\n\r\nCoinJar provides free and almost instant deposits and withdrawals using Faster Payments Services in the UK and Osko / PayID / NPP in Australia, allowing new customers to start trading in minutes across AUD, GBP and 30 cryptocurrencies. You can also buy crypto instantly using a Visa or Mastercard.\r\n\r\nCoinJar’s fees start at 0% for market orders on exchange.coinjar.com and go up to 2% for credit and debit card purchases – one of the lowest rates worldwide.\r\n\r\nCoinJar Card Mastercard is a fully-featured Mastercard – with both Apple Pay and Google Pay integration – that lets customers make purchases by converting their cryptocurrencies into AUD or GBP, everywhere Mastercard is accepted.\r\n\r\nDesigned for ASX and FTSE listed companies, CoinJar Clear is a white-label cryptocurrency solution used by stock trading, cashback, buy now pay later and other financial services companies.",
    "url": "https://www.coinjar.com/",
    "image": "https://assets.coingecko.com/markets/images/176/small/Logomark_2022200h_thumb.png?1657688357",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 98,
    "trade_volume_24h_btc": 56.467197823963666,
    "trade_volume_24h_btc_normalized": 56.467197823963666
  },
  {
    "id": "bitlo",
    "name": "Bitlo",
    "year_established": 2018,
    "country": "Turkey",
    "description": "",
    "url": "https://www.bitlo.com/",
    "image": "https://assets.coingecko.com/markets/images/968/small/bitlo-logo-b.png?1677732049",
    "has_trading_incentive": false,
    "trust_score": 6,
    "trust_score_rank": 99,
    "trade_volume_24h_btc": 30.16994097182882,
    "trade_volume_24h_btc_normalized": 30.16994097182882
  },
  {
    "id": "zaif",
    "name": "Zaif",
    "year_established": 2015,
    "country": "Japan",
    "description": null,
    "url": "https://zaif.jp/",
    "image": "https://assets.coingecko.com/markets/images/99/small/zaif.png?1519627467",
    "has_trading_incentive": null,
    "trust_score": 6,
    "trust_score_rank": 100,
    "trade_volume_24h_btc": 25.432187461185606,
    "trade_volume_24h_btc_normalized": 25.432187461185606
  }
]